#!/bin/sh
export SOL_BENCH_DIR=$SOLUTIONS_BENCH_DIR/DataMPI
export SOL_TEMPLATE_DIR=$TEMPLATES_DIR/DataMPI
export SOL_SGE_DAEMONS_DIR=$SGE_DAEMONS_DIR/DataMPI
export SOL_STD_DAEMONS_DIR=$STD_DAEMONS_DIR/DataMPI
export SOL_SBIN_DIR=$SOLUTION_HOME/bin
export SOL_CONF_DIR_SRC=$SOLUTION_HOME/conf
export SOL_CONF_DIR=$SOLUTION_REPORT_DIR/conf/datampi
export SOL_LOG_DIR=$SOLUTION_REPORT_DIR/logs/datampi
export MASTERFILE=$SOL_CONF_DIR/master
export SLAVESFILE=$SOL_CONF_DIR/hostfile

#MPI
$LOAD_MPI_COMMAND

#DATAMPI
export DATAMPI_HOME=$SOLUTION_HOME
export MPI_D_CONF_PATH=$SOL_CONF_DIR
export DATAMPI_CONF_DIR=$SOL_CONF_DIR
export PATH=$DATAMPI_HOME/bin:$PATH
export HOSTFILE=$SLAVESFILE

#HADOOP environment variables
export HADOOP_HOME=$DATAMPI_HADOOP_HOME
export HADOOP_CONF_DIR_SRC=$HADOOP_HOME/conf
export HADOOP_CONF_DIR=$SOLUTION_REPORT_DIR/conf/hadoop
export HADOOP_LOG_DIR=$SOLUTION_REPORT_DIR/logs/hadoop
export HADOOP_TEMPLATE_DIR=$TEMPLATES_DIR/Hadoop
export HADOOP_SGE_DAEMONS_DIR=$SGE_DAEMONS_DIR/Hadoop
export HADOOP_STD_DAEMONS_DIR=$STD_DAEMONS_DIR/Hadoop
export HADOOP_SBIN_DIR=$HADOOP_HOME/bin
export PATH=$HADOOP_HOME/bin:$PATH

export HADOOP_MR_VERSION="MR1"

#Configuracion
export OLD_GEN_CONFIG_SCRIPT=$GEN_CONFIG_SCRIPT
export GEN_CONFIG_SCRIPT=$SOLUTION_DIR/bin/gen-config.sh

#Daemons
export OLD_COPY_DAEMONS_SCRIPT=$COPY_DAEMONS_SCRIPT
export COPY_DAEMONS_SCRIPT=$SOLUTION_DIR/bin/copy-daemons.sh

add_conf_param "hadoop_conf_path" $HADOOP_CONF_DIR
