# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

spark.master spark://$master:7077
spark.driver.host $master
spark.driver.cores $spark_driver_cores
spark.driver.memory $spark_driver_memorym
spark.driver.memoryOverhead $spark_driver_memOverheadm
spark.executor.instances $spark_executor_instances
spark.executor.cores $spark_executor_cores
spark.executor.memory $spark_executor_memorym
spark.executor.memoryOverhead $spark_executor_memOverheadm
spark.yarn.am.cores $spark_yarn_am_cores
spark.yarn.am.memory $spark_yarn_am_memorym
spark.yarn.am.memoryOverhead $spark_yarn_am_memOverheadm
spark.memory.fraction $spark_memory_fraction
spark.memory.storageFraction $spark_memory_storage_fraction
spark.driver.extraJavaOptions -Djava.io.tmpdir=$tmp_dir $java_jpms_opts
spark.executor.extraJavaOptions -Djava.io.tmpdir=$tmp_dir $java_jpms_opts
spark.executor.extraLibraryPath $hadoop_home/lib/native
spark.driver.userClassPathFirst true
spark.executor.userClassPathFirst true
spark.default.parallelism $spark_default_parallelism
spark.local.dir	$spark_local_dirs
spark.shuffle.compress $spark_shuffle_compress
spark.shuffle.spill.compress $spark_shuffle_spill_compress
spark.broadcast.compress $spark_broadcast_compress
spark.rdd.compress $spark_rdd_compress
spark.io.compression.codec $spark_io_compression_codec
spark.sql.parquet.compression.codec $spark_sql_parquet_compression_codec
spark.serializer org.apache.spark.serializer.$spark_serializer
spark.kryo.unsafe $spark_kryo_unsafe
spark.kryo.registrationRequired	$spark_kryo_registrationRequired
spark.kryoserializer.buffer.max	$spark_kryo_buffer_maxm
spark.history.fs.logDirectory $storage_backend_uri/$spark_history_server_dir
spark.eventLog.enabled $spark_event_log
spark.eventLog.dir $storage_backend_uri/$spark_history_server_dir
spark.yarn.historyServer.address $master:18080
spark.speculation false
spark.network.timeout $spark_network_timeouts
spark.worker.timeout $spark_network_timeout
spark.executor.heartbeatInterval $spark_executor_heartbeats
spark.sql.adaptive.enabled $spark_sql_aqe
spark.sql.shuffle.partitions $spark_sql_shuffle_partitions
spark.sql.adaptive.coalescePartitions.enabled $spark_aqe_coalesce_partitions
spark.sql.adaptive.advisoryPartitionSizeInBytes $spark_aqe_partition_size
