#!/bin/bash

export SOLUTION_CONF_DIR_SRC="$SOLUTION_HOME/etc/hadoop"
export SOLUTION_CONF_DIR="$SOLUTION_REPORT_DIR/conf/hadoop"
export SOLUTION_LOG_DIR="$SOLUTION_REPORT_DIR/logs/hadoop"
export SOLUTION_TEMPLATE_DIR=$TEMPLATES_DIR/RDMA-Hadoop-3
export SOLUTION_BENCH_DIR="$BENCHMARKS_DIR/Hadoop"
export MASTERFILE="$SOLUTION_CONF_DIR/masters"
export HADOOP_WORKERSFILE"$SOLUTION_CONF_DIR/workers"
export WORKERSFILE="$HADOOP_WORKERSFILE"

#HADOOP environment variables
export HADOOP_HOME="$SOLUTION_HOME"
export HADOOP_CONF_DIR_SRC="$SOLUTION_CONF_DIR_SRC"
export HADOOP_CONF_DIR="$SOLUTION_CONF_DIR"
export HADOOP_LOG_DIR="$SOLUTION_LOG_DIR"
export HADOOP_TEMPLATE_DIR="$SOLUTION_TEMPLATE_DIR"
export HADOOP_WORKERSFILE="$WORKERSFILE"
export PATH="$HADOOP_HOME/bin:$PATH"
export HADOOP_SSH_OPTS="${BDEV_SSH_OPTS}"
export HADOOP_VERSION="${HADOOP_HOME##*/}"
export HADOOP_MAJOR_VERSION="${HADOOP_VERSION%.*}"
export HADOOP_SERIES=3
