#!/bin/bash
export SOL_BENCH_DIR=$BENCHMARKS_DIR/Hadoop
export SOL_CONF_DIR_SRC=$SOLUTION_HOME/etc/hadoop
export SOL_CONF_DIR=$SOLUTION_REPORT_DIR/etc/hadoop
export SOL_LOG_DIR=$SOLUTION_REPORT_DIR/logs
export SOL_TEMPLATE_DIR=$TEMPLATES_DIR/RDMA-Hadoop-3
export SOL_GEN_CONFIG_SCRIPT=$GEN_CONFIG_SCRIPT
export MASTERFILE=$SOL_CONF_DIR/masters
export WORKERSFILE=$SOL_CONF_DIR/workers

#HADOOP environment variables
export HADOOP_HOME=$SOLUTION_HOME
export HADOOP_CONF_DIR=$SOL_CONF_DIR
export HADOOP_LOG_DIR=$SOL_LOG_DIR
export PATH=$HADOOP_HOME/bin:$PATH
export HADOOP_VERSION=${HADOOP_HOME##*/}
export HADOOP_MAJOR_VERSION=${HADOOP_VERSION%.*}
export HADOOP_SERIES=3
export HADOOP_SSH_OPTS="${BDEV_SSH_OPTS}"
