#!/bin/bash
export SOLUTION_CONF_DIR_SRC=$SOLUTION_HOME/etc/hadoop
export SOLUTION_CONF_DIR=$SOLUTION_REPORT_DIR/etc/hadoop
export SOLUTION_LOG_DIR=$SOLUTION_REPORT_DIR/logs
export SOLUTION_BENCH_DIR=$BENCHMARKS_DIR/Hadoop

#HADOOP environment variables
export HADOOP_HOME=$SOLUTION_HOME
export HADOOP_CONF_DIR=$SOLUTION_CONF_DIR
export HADOOP_LOG_DIR=$SOLUTION_LOG_DIR
export PATH=$HADOOP_HOME/bin:$PATH
export HADOOP_VERSION=${HADOOP_HOME##*/}
export HADOOP_MAJOR_VERSION=${HADOOP_VERSION%.*}
export HADOOP_SERIES=${HADOOP_VERSION%%.*}
export HADOOP_SSH_OPTS="${BDEV_SSH_OPTS}"

if [[ $HADOOP_SERIES == "3" ]]; then
	export SOLUTION_TEMPLATE_DIR=$TEMPLATES_DIR/Hadoop-YARN-3
	export HADOOP_WORKERSFILE=$SOLUTION_CONF_DIR/workers
elif [[ $HADOOP_SERIES == "2" ]]; then
	export SOLUTION_TEMPLATE_DIR=$TEMPLATES_DIR/Hadoop-YARN
	export HADOOP_WORKERSFILE=$SOLUTION_CONF_DIR/slaves
	export YARN_CONF_DIR=$HADOOP_CONF_DIR
	export YARN_LOG_DIR=$HADOOP_LOG_DIR
else
	m_exit "Hadoop version is not supported: $HADOOP_VERSION"
fi
