#!/bin/sh
export SOL_BENCH_DIR=$SOLUTIONS_BENCH_DIR/Hadoop
export SOL_TEMPLATE_DIR=$TEMPLATES_DIR/Hadoop
export SOL_SGE_DAEMONS_DIR=$SGE_DAEMONS_DIR/Hadoop
export SOL_STD_DAEMONS_DIR=$STD_DAEMONS_DIR/Hadoop
export SOL_SBIN_DIR=$SOLUTION_HOME/bin
export SOL_CONF_DIR_SRC=$SOLUTION_HOME/conf
export SOL_CONF_DIR=$SOLUTION_REPORT_DIR/conf
export SOL_LOG_DIR=$SOLUTION_REPORT_DIR/logs
export MASTERFILE=$SOL_CONF_DIR/masters
export SLAVESFILE=$SOL_CONF_DIR/slaves

#HADOOP environment variables
export HADOOP_HOME=$SOLUTION_HOME
export HADOOP_CONF_DIR=$SOL_CONF_DIR
export PATH=$HADOOP_HOME/bin:$PATH

export HADOOP_MR_VERSION="MR1"
